name: Crypto Listing Notifier

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'

jobs:
  check-listings:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Run script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python main.py
      continue-on-error: true

    - name: Display script output
      if: failure()
      run: cat $GITHUB_WORKSPACE/main.py

    - name: Display logs
      if: failure()
      run: cat $GITHUB_WORKSPACE/logs/* || true
